name: Basera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  dropdown_button2: ^2.3.9
  flutter_animate: ^4.5.0
  dio: ^5.7.0
  get_it: ^8.0.0
  dartz: ^0.10.1
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.2
  toggle_switch: ^2.3.0
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  animated_notch_bottom_bar: ^1.0.3
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/animation/sent-email-animation.json
    - lib/assets/animation/error-animation.json

